<?php
/**
 * Al Asail Equine — English Language Dictionary
 */
return [
    // Header
    'home' => 'Home',
    'shop' => 'Shop',
    'categories' => 'Categories',
    'offers' => 'Offers',
    'search_placeholder' => 'Search veterinary products...',
    'login' => 'Login',
    'logout' => 'Logout',
    'admin' => 'Admin Panel',
    'my_account' => 'My Account',
    'menu' => 'Menu',
    'search' => 'Search',
    'cart' => 'Cart',
    'navigation' => 'Navigation',
    'tap_to_close' => 'Tap to close menu',
    'account' => 'Account',

    // Cart Popup
    'product_added' => 'Product added to cart successfully',
    'next_step' => 'What would you like to do next?',
    'go_to_cart' => '🛒 Go to Cart',
    'continue_shopping' => 'Continue Shopping',

    // Footer
    'footer_desc' => 'Your trusted partner for professional equine veterinary supplies, horse medicines, supplements, horseshoes, and riding equipment in Jordan.',
    'contact_whatsapp' => 'WhatsApp',
    'contact_email' => 'Email',
    'support' => 'Support',
    'faq' => 'FAQ',
    'shipping_policy' => 'Shipping Policy',
    'returns_refunds' => 'Returns & Refunds',
    'privacy_policy' => 'Privacy Policy',
    'email_us' => 'Email Us',
    'whatsapp_chat' => 'WhatsApp Chat',
    'accepted_payments' => 'Accepted Payments',
    'visa_card' => 'Visa Card',
    'cash_on_delivery' => 'Cash on Delivery',
    'rights_reserved' => 'All rights reserved. Jordan.',

    // Homepage / General
    'featured_products' => 'Featured Products',
    'deal_of_the_day' => 'Deal of the Day',
    'testimonials' => 'What Clients Say',
    'quick_view' => 'Quick View',
    'add_to_cart' => 'Add to Cart 🛒',
    'out_of_stock' => 'Out of Stock ❌',
    'limited_offer' => 'Limited Time Offer',
    'jod' => 'JOD',
    'all_categories' => 'All Categories',
    'explore_shop' => 'Explore Shop',
    
    // Home Page Translation Strings
    'hero_title' => 'Professional<br>Veterinary Medical Care<br><span class="hero-title-accent">For Horses.</span>',
    'hero_desc' => 'Your trusted partner for certified equine veterinary supplies, medicines, and supplements — delivered to you with care and professionalism in Jordan.',
    'shop_products' => 'Shop Products 🐎',
    'view_offers' => 'View Offers ⚕️',
    'products_stat' => 'Veterinary Products',
    'horses_treated_stat' => 'Horses Treated',
    'vet_rating_stat' => 'Veterinary Rating',
    
    'easy_returns' => 'Easy Returns',
    'easy_returns_desc' => '7-day return guarantee',
    'vet_approved' => 'Vet Approved',
    'vet_approved_desc' => 'All products are certified',
    'expert_support' => 'Expert Support',
    'expert_support_desc' => 'Veterinary consultations',
    'secure_payment' => 'Secure Payment',
    'secure_payment_desc' => 'Fully encrypted transactions',
    
    'browse_by_category' => 'Browse by Category',
    'equine_supplies' => 'Equine Veterinary Supplies',
    'equine_supplies_sub' => 'Find certified, high-quality products for all aspects of equine health and care.',
    'recommended' => 'Recommended',
    'featured_sub' => 'Top trusted medical choices by veterinarians and horse owners.',
    'new_products' => 'New Arrivals 🌟',
    'new_products_sub' => 'The latest additions to our comprehensive equine care and health catalog.',
    'our_community' => 'Our Community',
    'what_owners_say' => 'What Horse Owners Say',
    'what_owners_say_sub' => 'Feedback from veterinarians and horse owners who trust Al Asail for their horses.',
    'stay_updated' => 'Stay Updated on Horse Health 🐎',
    'stay_updated_sub' => 'Subscribe to receive veterinary medical tips, new product alerts, and exclusive offers.',
    'enter_email' => 'Enter your email address',
    'subscribe' => 'Subscribe Now',
    'items_count' => 'Product(s)',
    'no_products_found_featured' => 'No featured products found.',
    'run_migration_admin' => 'Please run initialization from the Admin Panel to seed the data.',
    'hours' => 'Hours',
    'mins' => 'Mins',
    'secs' => 'Secs',
    
    // Shop Page
    'filter_by_price' => 'Filter by Price',
    'max_price' => 'Max Price:',
    'showing_results' => 'Showing results for',
    'no_products_found' => 'No products found matching your search.',
    'all_products' => 'All Products',
    'all_in' => 'All in',

    // Product Details
    'stock_status' => 'Availability:',
    'in_stock' => 'In Stock',
    'description' => 'Description',
    'similar_products' => 'Similar Products',
    'quantity' => 'Quantity:',

    // Authentication Page
    'welcome_back' => 'Welcome Back 👋',
    'login_sub' => 'Log in to your Al Asail account',
    'email_address' => 'Email Address',
    'password' => 'Password',
    'login_btn' => '🔒 Log In',
    'dont_have_account' => "Don't have an account?",
    'create_one' => 'Create one →',
    'create_account' => 'Create Account 🚀',
    'join_us' => 'Join Al Asail and start shopping',
    'first_name' => 'First Name',
    'last_name' => 'Last Name',
    'confirm_password' => 'Confirm Password',
    'register_btn' => '🚀 Create Account',
    'already_have_account' => 'Already have an account? Log in →',
    'forgot_password' => 'Forgot Password?',
    'or_sign_in_with' => 'Or continue with',
    
    // Forgot / Reset Password
    'forgot_password_title' => 'Forgot Password 🔒',
    'forgot_password_sub' => 'Enter your email to receive a password reset link',
    'send_reset_link' => '📧 Send Reset Link',
    'back_to_login' => '← Back to Login',
    'reset_password_title' => 'Reset Password 🔑',
    'reset_password_sub' => 'Enter your new password below',
    'new_password' => 'New Password',
    'reset_btn' => '🔑 Reset Password',
    'check_email_success' => 'A password reset link has been simulated for your email below.',
    
    // Account Dashboard
    'hello' => 'Hello',
    'dashboard' => 'Dashboard',
    'orders' => 'Orders',
    'addresses' => 'Addresses',
    'account_details' => 'Account Details',
    'phone' => 'Phone',
    'city' => 'City',
    'address' => 'Address',
    'update_profile' => 'Update Profile',
    'change_password' => 'Change Password',
    'current_password' => 'Current Password',
    'update_btn' => 'Save Changes',
    'order_num' => 'Order Number',
    'date' => 'Date',
    'status' => 'Status',
    'total' => 'Total',
    'actions' => 'Actions',
    'view_details' => 'View',
    'no_orders' => "You haven't placed any orders yet.",

    // Cart / Checkout
    'shopping_cart' => 'Shopping Cart',
    'subtotal' => 'Subtotal',
    'shipping' => 'Shipping',
    'checkout' => 'Checkout',
    'order_summary' => 'Order Summary',
    'billing_details' => 'Billing Details',
    'payment_method' => 'Payment Method',
    'order_notes' => 'Order Notes (optional)',
    'place_order' => 'Place Order 🐎',
    'empty_cart' => 'Your cart is empty.',
    'free' => 'Free',

    // Dynamic database categories
    'Veterinary Treatments for Horses' => 'Veterinary Treatments for Horses',
    'Supplements & Nutrition' => 'Supplements & Nutrition',
    'Horseshoes' => 'Horseshoes',
    'Horse & Rider Equipment' => 'Horse & Rider Equipment',
    'Veterinary Consumables' => 'Veterinary Consumables',
    'Horse Feed & Fodder' => 'Horse Feed & Fodder',
    'Feeding & Watering' => 'Feeding & Watering',
    'Milking Equipment' => 'Milking Equipment',
    'Egg Incubators' => 'Egg Incubators',
    'Injection Equipment' => 'Injection Equipment',
    'Pet Treats' => 'Pet Treats',

    // Dynamic database subcategories
    'Antibiotics' => 'Antibiotics',
    'Painkillers' => 'Painkillers',
    'Antiparasitics' => 'Antiparasitics',
    'Deworming Syrups' => 'Deworming Syrups',
    'Supplements & Vitamins' => 'Supplements & Vitamins',
    'Insecticides' => 'Insecticides',
    'Hoof Care' => 'Hoof Care',
    'Digestive System Care' => 'Digestive System Care',
    'Muscle Care' => 'Muscle Care',
    'Postpartum & Foaling Care' => 'Postpartum & Foaling Care',
    'Respiratory System Care' => 'Respiratory System Care',
    'Joint & Mobility Care' => 'Joint & Mobility Care',
    'Bone & Joint Care' => 'Bone & Joint Care',
    'Standard Shoes' => 'Standard Shoes',
    'Nails' => 'Nails',
    'Therapeutic Shoes' => 'Therapeutic Shoes',
    
    // New Homepage Keys
    'vet_recommended' => 'Vet Recommended',
    'verified_review' => 'Verified 4.9★ Review Score',
    'subscribe_alert' => 'Thank you for subscribing! You will receive equine health updates and exclusive offers in your inbox.',
    'testi1_text' => '"Al Asail has been our go-to supplier for all equine veterinary needs. The Penicillin G they supply is authentic and arrives quickly. Outstanding service every time!"',
    'testi1_author' => 'Dr. Khalid Al-Rashid',
    'testi1_loc' => 'Amman, Jordan',
    'testi2_text' => '"I ordered the BioTin Hoof Supplement and within 6 weeks my mare\'s hooves improved dramatically. Fast shipping and genuinely professional packaging."',
    'testi2_author' => 'Sara Al-Mansouri',
    'testi2_loc' => 'Zarqa, Jordan',
    'testi3_text' => '"The therapeutic horseshoes saved my racing horse from a serious hoof condition. Saved JOD 200 vs. the local farrier. Al Asail\'s product quality is unmatched."',
    'testi3_author' => 'Faisal Al-Nabulsi',
    'testi3_loc' => 'Irbid, Jordan',

    // Shop Page Specific Keys
    'showing' => 'Showing',
    'of' => 'of',
    'products' => 'products',
    'in' => 'in',
    'close' => 'Close',
    'any' => 'Any',
    'apply' => 'Apply',
    'clear' => 'Clear',
    'filters' => 'Filters & Categories',
    'sort_by' => 'Sort By',
    'newest' => 'Newest',
    'popular' => 'Most Popular',
    'price_low_high' => 'Price: Low to High',
    'price_high_low' => 'Price: High to Low',
    'clear_filters' => 'Clear Filters',
    'adjust_filters_desc' => 'Try adjusting your filters or search term',

    // Product Details Specific Keys
    'reviews' => 'reviews',
    'off' => 'OFF',
    'in_stock_msg' => 'In Stock',
    'units_available' => 'units available',
    'free_delivery_over' => 'Free delivery on orders over',
    'returns_policy' => '7-day hassle-free returns',
    'warranty_policy' => '2-year manufacturer warranty',
    'secure_encrypted' => 'Secure, encrypted payment',

    // Order statuses
    'pending' => 'Pending',
    'processing' => 'Processing',
    'shipped' => 'Shipped',
    'delivered' => 'Delivered',
    'cancelled' => 'Cancelled',

    // Payment methods
    'cod' => 'Cash on Delivery',
    'visa' => 'Visa Card',

    // Cart Keys
    'empty_cart_title' => 'Your cart is empty',
    'empty_cart_desc' => "You haven't added any veterinary products yet. Browse our equine health catalog!",
    'start_shopping' => 'Start Shopping 🐎',
    'product_col' => 'Product',
    'price_col' => 'Price',
    'quantity_col' => 'Quantity',
    'items_count_suffix' => 'Product(s)',
    'add_more_for_free_shipping' => 'Add %s more for free shipping!',
    'free_shipping_achieved' => '🎉 You have free shipping!',
    'coupon_code' => 'Coupon code',
    'proceed_to_checkout' => 'Proceed to Checkout →',
    'secure_checkout' => '🔒 Secure Checkout Guaranteed',

    // Checkout Keys
    'contact_info' => 'Contact Information',
    'shipping_address' => 'Shipping Address',
    'country' => 'Country',
    'delivery_instructions' => 'Any special delivery instructions...',
    'cod_desc' => 'Pay when your order arrives — Free of charge',
    'visa_desc' => 'Pay securely with your Visa credit/debit card',
    'order_review' => 'Order Review',
    'qty_label' => 'Qty',
    'place_order_btn' => 'Place Order — %s',
    'info_secure' => '🔒 Your information is secure & encrypted',
    'err_first_name' => 'First name is required.',
    'err_last_name' => 'Last name is required.',
    'err_email' => 'Valid email is required.',
    'err_phone' => 'Phone number is required.',
    'err_address' => 'Street address is required.',
    'err_city' => 'City is required.',

    // My Account Keys
    'my_orders' => 'My Orders',
    'profile' => 'Profile',
    'profile_updated' => 'Profile updated successfully!',
    'err_current_password' => 'Current password is incorrect.',
    'err_password_length' => 'New password must be at least 6 characters.',
    'err_password_match' => 'New passwords do not match.',
    'password_updated' => 'Password updated successfully!',
    'welcome_back_user' => 'Welcome back, %s! 👋',
    'account_summary' => "Here's a summary of your account activity",
    'total_orders' => 'Total Orders',
    'delivered' => 'Delivered',
    'total_spent' => 'Total Spent',
    'recent_orders' => 'Recent Orders',
    'no_orders_yet' => 'No orders yet',
    'start_shopping_desc' => 'Start shopping to see your orders here',
    'shop_now' => 'Shop Now',
    'payment' => 'Payment',
    'email_cannot_change' => 'Email cannot be changed',
    'min_6_chars' => 'Min 6 characters',
    'items_count' => 'Items',
];

