<?php
/**
 * Al Asail Equine — Arabic Language Dictionary
 */
return [
    // Header
    'home' => 'الرئيسية',
    'shop' => 'المتجر',
    'categories' => 'الأقسام',
    'offers' => 'العروض',
    'search_placeholder' => 'ابحث عن المستلزمات الطبية والبيطرية...',
    'login' => 'تسجيل الدخول',
    'logout' => 'تسجيل الخروج',
    'admin' => 'لوحة التحكم',
    'my_account' => 'حسابي',
    'menu' => 'القائمة',
    'search' => 'بحث',
    'cart' => 'السلة',
    'navigation' => 'التنقل',
    'tap_to_close' => 'انقر لإغلاق القائمة',
    'account' => 'الحساب',

    // Cart Popup
    'product_added' => 'تم إضافة المنتج إلى السلة بنجاح',
    'next_step' => 'ماذا تريد أن تفعل بعد ذلك؟',
    'go_to_cart' => '🛒 الذهاب إلى السلة',
    'continue_shopping' => 'مواصلة التسوق',

    // Footer
    'footer_desc' => 'شريكك الموثوق للمستلزمات البيطرية المهنية للخيول، أدوية الخيل، المكملات الغذائية، الحداوي، ومعدات الفارس في الأردن.',
    'contact_whatsapp' => 'واتساب',
    'contact_email' => 'البريد الإلكتروني',
    'support' => 'الدعم الفني',
    'faq' => 'الأسئلة الشائعة',
    'shipping_policy' => 'سياسة الشحن',
    'returns_refunds' => 'الاسترجاع والاسترداد',
    'privacy_policy' => 'سياسة الخصوصية',
    'email_us' => 'راسلنا إلكترونياً',
    'whatsapp_chat' => 'محادثة واتساب',
    'accepted_payments' => 'طرق الدفع المقبولة',
    'visa_card' => 'بطاقة فيزا',
    'cash_on_delivery' => 'الدفع عند الاستلام',
    'rights_reserved' => 'جميع الحقوق محفوظة. الأردن.',

    // Homepage / General
    'featured_products' => 'المنتجات المميزة',
    'deal_of_the_day' => 'عرض اليوم المميز',
    'testimonials' => 'آراء عملائنا الكرام',
    'quick_view' => 'عرض سريع',
    'add_to_cart' => 'إضافة إلى السلة 🛒',
    'out_of_stock' => 'غير متوفر ❌',
    'limited_offer' => 'عرض لفترة محدودة',
    'jod' => 'دينار أردني',
    'all_categories' => 'جميع الأقسام',
    'explore_shop' => 'تصفح المتجر',
    
    // Home Page Translation Strings
    'hero_title' => 'رعاية طبية<br>بيطرية مهنية<br><span class="hero-title-accent">للخيول.</span>',
    'hero_desc' => 'شريكك الموثوق للمستلزمات والأدوية والمكملات البيطرية المعتمدة للخيول — نصلك بعناية واحترافية في الأردن.',
    'shop_products' => 'تسوق المنتجات 🐎',
    'view_offers' => 'عرض العروض ⚕️',
    'products_stat' => 'مستحضر بيطري',
    'horses_treated_stat' => 'خيل معالجة',
    'vet_rating_stat' => 'تقييم الأطباء',
    
    'easy_returns' => 'استرجاع سهل',
    'easy_returns_desc' => 'ضمان استرجاع 7 أيام',
    'vet_approved' => 'معتمد بيطرياً',
    'vet_approved_desc' => 'جميع المنتجات مرخصة',
    'expert_support' => 'دعم الخبراء',
    'expert_support_desc' => 'استشارات طبية بيطرية',
    'secure_payment' => 'دفع آمن',
    'secure_payment_desc' => 'عمليات مشفرة بالكامل',
    
    'browse_by_category' => 'تصفح حسب الفئات',
    'equine_supplies' => 'المستلزمات البيطرية للخيول',
    'equine_supplies_sub' => 'اعثر على منتجات معتمدة وعالية الجودة لكل جوانب صحة ورعاية الخيول.',
    'recommended' => 'موصى به',
    'featured_sub' => 'أفضل خيارات المنتجات الطبية الموثوقة من الأطباء البيطريين ومربي الخيل.',
    'new_products' => 'وصل حديثاً 🌟',
    'new_products_sub' => 'أحدث الإضافات لمجموعتنا الشاملة لرعاية وصحة الخيول.',
    'our_community' => 'مجتمعنا الكرام',
    'what_owners_say' => 'ماذا يقول مربو الخيول عنّا',
    'what_owners_say_sub' => 'آراء الأطباء البيطريين وأصحاب الخيل الذين يثقون بالأصيل لرعاية خيولهم.',
    'stay_updated' => 'ابق على اطلاع بصحة خيلك 🐎',
    'stay_updated_sub' => 'اشترك لتلقي النصائح الطبية البيطرية، تنبيهات المنتجات الجديدة، والعروض الحصرية.',
    'enter_email' => 'أدخل عنوان بريدك الإلكتروني',
    'subscribe' => 'اشترك الآن',
    'items_count' => 'منتج',
    'no_products_found_featured' => 'لم يتم العثور على منتجات مميزة.',
    'run_migration_admin' => 'يرجى تشغيل التهيئة من لوحة التحكم لتغذية البيانات.',
    'hours' => 'ساعات',
    'mins' => 'دقائق',
    'secs' => 'ثواني',
    
    // Shop Page
    'filter_by_price' => 'تصفية حسب السعر',
    'max_price' => 'الحد الأقصى للسعر:',
    'showing_results' => 'عرض نتائج البحث عن',
    'no_products_found' => 'لم يتم العثور على منتجات تطابق بحثك.',
    'all_products' => 'جميع المنتجات',
    'all_in' => 'كل المنتجات في',

    // Product Details
    'stock_status' => 'حالة التوفر:',
    'in_stock' => 'متوفر في المخزن',
    'description' => 'الوصف التفصيلي',
    'similar_products' => 'منتجات مشابهة قد تعجبك',
    'quantity' => 'الكمية:',

    // Authentication Page
    'welcome_back' => 'مرحباً بك مجدداً 👋',
    'login_sub' => 'قم بتسجيل الدخول إلى حسابك في الأصيل للخيول',
    'email_address' => 'البريد الإلكتروني',
    'password' => 'كلمة المرور',
    'login_btn' => '🔒 تسجيل الدخول',
    'dont_have_account' => 'ليس لديك حساب؟',
    'create_one' => 'أنشئ حساباً جديداً الآن ←',
    'create_account' => 'إنشاء حساب جديد 🚀',
    'join_us' => 'انضم إلى عائلة الأصيل وابدأ التسوق الآن',
    'first_name' => 'الاسم الأول',
    'last_name' => 'الاسم الأخير',
    'confirm_password' => 'تأكيد كلمة المرور',
    'register_btn' => '🚀 تسجيل الحساب الجديد',
    'already_have_account' => 'لديك حساب بالفعل؟ سجل دخولك ←',
    'forgot_password' => 'نسيت كلمة المرور؟',
    'or_sign_in_with' => 'أو الدخول بواسطة',
    
    // Forgot / Reset Password
    'forgot_password_title' => 'استعادة كلمة المرور 🔒',
    'forgot_password_sub' => 'أدخل بريدك الإلكتروني لإرسال رابط إعادة تعيين كلمة المرور',
    'send_reset_link' => '📧 إرسال رابط الاستعادة',
    'back_to_login' => '← العودة لتسجيل الدخول',
    'reset_password_title' => 'تعيين كلمة المرور الجديدة 🔑',
    'reset_password_sub' => 'أدخل كلمة المرور الجديدة الخاصة بك أدناه',
    'new_password' => 'كلمة المرور الجديدة',
    'reset_btn' => '🔑 حفظ وتعيين كلمة المرور',
    'check_email_success' => 'تم محاكاة إرسال رابط استعادة كلمة المرور لبريدك الإلكتروني أدناه بنجاح.',
    
    // Account Dashboard
    'hello' => 'أهلاً بك',
    'dashboard' => 'لوحة التحكم',
    'orders' => 'الطلبات والطلبيات',
    'addresses' => 'العناوين المحفوظة',
    'account_details' => 'بيانات وتفاصيل الحساب',
    'phone' => 'رقم الهاتف',
    'city' => 'المدينة / المحافظة',
    'address' => 'العنوان التفصيلي',
    'update_profile' => 'تحديث البيانات الشخصية',
    'change_password' => 'تغيير كلمة المرور',
    'current_password' => 'كلمة المرور الحالية',
    'update_btn' => 'حفظ التعديلات',
    'order_num' => 'رقم الطلب',
    'date' => 'التاريخ',
    'status' => 'الحالة',
    'total' => 'الإجمالي',
    'actions' => 'الإجراءات',
    'view_details' => 'عرض التفاصيل',
    'no_orders' => 'لم تقم بإجراء أي طلبات حتى الآن.',

    // Cart / Checkout
    'shopping_cart' => 'سلة التسوق',
    'subtotal' => 'المجموع الفرعي',
    'shipping' => 'الشحن والتوصيل',
    'checkout' => 'إتمام الطلب والدفع',
    'order_summary' => 'ملخص الطلبية',
    'billing_details' => 'تفاصيل الفاتورة والشحن',
    'payment_method' => 'طريقة الدفع المفضلة',
    'order_notes' => 'ملاحظات الطلب (اختياري)',
    'place_order' => 'تأكيد الطلب الآن 🐎',
    'empty_cart' => 'سلة التسوق الخاصة بك فارغة حالياً.',
    'free' => 'مسترد / مجاني',

    // Dynamic database categories
    'Veterinary Treatments for Horses' => 'علاجات الخيول البيطرية',
    'Supplements & Nutrition' => 'المكملات الغذائية والتغذية',
    'Horseshoes' => 'حداوي الخيل',
    'Horse & Rider Equipment' => 'معدات الخيل والفارس',
    'Veterinary Consumables' => 'المستهلكات الطبية البيطرية',
    'Horse Feed & Fodder' => 'أعلاف وأغذية الخيول',
    'Feeding & Watering' => 'معالف و مشارب',
    'Milking Equipment' => 'حلابات أبقار وأغنام ومحالب مركزية',
    'Egg Incubators' => 'فقاسات البيض',
    'Injection Equipment' => 'معدات حقن',
    'Pet Treats' => 'مكافأت القطط والكلاب',

    // Dynamic database subcategories
    'Antibiotics' => 'مضادات حيوية',
    'Painkillers' => 'مسكنات ومضادات التهاب',
    'Antiparasitics' => 'مضادات طفيليات',
    'Deworming Syrups' => 'مضادات الديدان المعوية',
    'Supplements & Vitamins' => 'فيتامينات ومكملات غذائية',
    'Insecticides' => 'مبيدات حشرية وطاردة',
    'Hoof Care' => 'العناية بالحوافر والعرج',
    'Digestive System Care' => 'العناية بالجهاز الهضمي والمغص',
    'Muscle Care' => 'العناية بالعضلات والتحمل',
    'Postpartum & Foaling Care' => 'العناية بعد الولادة والمهر',
    'Respiratory System Care' => 'العناية بالجهاز التنفسي والربو',
    'Joint & Mobility Care' => 'العناية بالمفاصل والغضاريف',
    'Bone & Joint Care' => 'العناية بالعظام والمفاصل',
    'Standard Shoes' => 'الحداوي القياسية',
    'Nails' => 'مسامير الحداوي',
    'Therapeutic Shoes' => 'الحداوي العلاجية والطبية',
    
    // New Homepage Keys
    'vet_recommended' => 'موصى به بيطرياً',
    'verified_review' => 'تقييم موثق 4.9★',
    'subscribe_alert' => 'شكراً لاشتراكك! ستتلقى تحديثات صحة الخيل والعروض الحصرية على بريدك الإلكتروني.',
    'testi1_text' => '"لقد كان الأصيل شريكنا الموثوق لجميع الاحتياجات الطبية والبيطرية لخيولنا. البنسلين الذي يزودوننا به أصيل ويصل بسرعة. خدمة متميزة في كل مرة!"',
    'testi1_author' => 'د. خالد الراشد',
    'testi1_loc' => 'عمان، الأردن',
    'testi2_text' => '"لقد طلبت مكمل BioTin للحوافر وخلال 6 أسابيع فقط تحسنت حوافر الفرس بشكل مذهل. شحن سريع وتغليف احترافي حقيقي."',
    'testi2_author' => 'سارة المنصوري',
    'testi2_loc' => 'الزرقاء، الأردن',
    'testi3_text' => '"لقد أنقذت الحداوي العلاجية حصان السباق الخاص بي من حالة حوافر خطيرة. وفرت 200 دينار مقارنة بالحداد المحلي. جودة منتجات الأصيل لا تضاهى."',
    'testi3_author' => 'فيصل النابلسي',
    'testi3_loc' => 'إربد، الأردن',

    // Shop Page Specific Keys
    'showing' => 'عرض',
    'of' => 'من',
    'products' => 'منتجات',
    'in' => 'في',
    'close' => 'إغلاق',
    'any' => 'الكل',
    'apply' => 'تطبيق',
    'clear' => 'مسح',
    'filters' => 'التصفية والتصنيف',
    'sort_by' => 'ترتيب حسب',
    'newest' => 'الأحدث وصولاً',
    'popular' => 'الأكثر شعبية',
    'price_low_high' => 'السعر: من الأقل إلى الأعلى',
    'price_high_low' => 'السعر: من الأعلى إلى الأقل',
    'clear_filters' => 'إزالة التصفية ✕',
    'adjust_filters_desc' => 'حاول تعديل فلاتر التصفية أو تغيير كلمة البحث لتجد نتائج أخرى.',

    // Product Details Specific Keys
    'reviews' => 'مراجعة',
    'off' => 'خصم',
    'in_stock_msg' => 'متوفر في المخزن',
    'units_available' => 'قطعة متوفرة',
    'free_delivery_over' => 'توصيل مجاني للطلبات فوق',
    'returns_policy' => 'استرجاع سهل ومضمون خلال 7 أيام',
    'warranty_policy' => 'ضمان المصنع والجودة المعتمدة',
    'secure_encrypted' => 'دفع آمن ومشفر بالكامل',

    // Order statuses
    'pending' => 'قيد الانتظار',
    'processing' => 'قيد المعالجة',
    'shipped' => 'تم الشحن',
    'delivered' => 'تم التوصيل',
    'cancelled' => 'ملغي',

    // Payment methods
    'cod' => 'الدفع عند الاستلام',
    'visa' => 'بطاقة فيزا',

    // Cart Keys
    'empty_cart_title' => 'سلة التسوق فارغة',
    'empty_cart_desc' => 'لم تقم بإضافة أي منتجات بيطرية حتى الآن. تصفح كتالوج صحة الخيل لدينا!',
    'start_shopping' => 'ابدأ التسوق الآن 🐎',
    'product_col' => 'المنتج',
    'price_col' => 'السعر',
    'quantity_col' => 'الكمية',
    'items_count_suffix' => 'منتج',
    'add_more_for_free_shipping' => 'أضف %s إضافية للحصول على شحن مجاني!',
    'free_shipping_achieved' => '🎉 لقد حصلت على شحن مجاني!',
    'coupon_code' => 'رمز الكوبون',
    'proceed_to_checkout' => 'الذهاب للدفع ←',
    'secure_checkout' => '🔒 الدفع آمن ومضمون بنسبة 100%',

    // Checkout Keys
    'contact_info' => 'معلومات الاتصال',
    'shipping_address' => 'عنوان الشحن',
    'country' => 'البلد',
    'delivery_instructions' => 'أي تعليمات خاصة بالتوصيل...',
    'cod_desc' => 'ادفع عند استلام طلبك — بدون رسوم إضافية',
    'visa_desc' => 'ادفع بأمان باستخدام بطاقة فيزا الائتمانية أو بطاقة الدفع',
    'order_review' => 'مراجعة الطلبية',
    'qty_label' => 'الكمية',
    'place_order_btn' => 'تأكيد الطلب — %s',
    'info_secure' => '🔒 بياناتك آمنة ومشفرة بالكامل',
    'err_first_name' => 'الاسم الأول مطلوب.',
    'err_last_name' => 'الاسم الأخير مطلوب.',
    'err_email' => 'البريد الإلكتروني المدخل غير صالح.',
    'err_phone' => 'رقم الهاتف مطلوب.',
    'err_address' => 'العنوان بالتفصيل مطلوب.',
    'err_city' => 'المدينة / المحافظة مطلوبة.',

    // My Account Keys
    'my_orders' => 'طلباتي',
    'profile' => 'الملف الشخصي',
    'profile_updated' => 'تم تحديث الملف الشخصي بنجاح!',
    'err_current_password' => 'كلمة المرور الحالية غير صحيحة.',
    'err_password_length' => 'يجب أن تتكون كلمة المرور الجديدة من 6 أحرف على الأقل.',
    'err_password_match' => 'كلمات المرور الجديدة غير متطابقة.',
    'password_updated' => 'تم تحديث كلمة المرور بنجاح!',
    'welcome_back_user' => 'مرحباً بك مجدداً، %s! 👋',
    'account_summary' => 'إليك ملخص لنشاط حسابك',
    'total_orders' => 'إجمالي الطلبات',
    'delivered' => 'تم التوصيل',
    'total_spent' => 'إجمالي المشتريات',
    'recent_orders' => 'الطلبات الأخيرة',
    'no_orders_yet' => 'لا توجد طلبات بعد',
    'start_shopping_desc' => 'ابدأ التسوق لتظهر طلباتك هنا',
    'shop_now' => 'تسوق الآن',
    'payment' => 'الدفع',
    'email_cannot_change' => 'لا يمكن تغيير البريد الإلكتروني',
    'min_6_chars' => '6 أحرف على الأقل',
    'items_count' => 'المنتجات',
];

